library(readr)
library(ggplot2)
dat <- read_tsv("lamp1_seed_out.txt")
dat <- t(dat)
dat <- data.frame(dat, stringsAsFactors=F)
dat <- apply(dat, 2, as.numeric)
dat <- dat[dat[,3] > 0,]
png("lamp1_seed_plot.png")
qplot(dat[,1], dat[,2], col=factor(dat[,3]), geom="line", xlab="time point", ylab="wavelet coeff")
dev.off()
